# Mirrors the language list in frontend/lib/services/i18n_service.dart (kSupportedLanguages).
# Used to tell Gemini which language to generate creative content in, since the frontend
# only ever sends an ISO-ish code (e.g. "pt", "zh-TW") and not a human-readable name.
LANGUAGE_NAMES = {
    'en': 'English',
    'zh': 'Chinese (Simplified)',
    'hi': 'Hindi',
    'es': 'Spanish',
    'ar': 'Arabic',
    'fr': 'French',
    'bn': 'Bengali',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'ur': 'Urdu',
    'id': 'Indonesian',
    'de': 'German',
    'ja': 'Japanese',
    'tr': 'Turkish',
    'ko': 'Korean',
    'vi': 'Vietnamese',
    'it': 'Italian',
    'th': 'Thai',
    'fil': 'Filipino',
    'fa': 'Persian',
    'pl': 'Polish',
    'uk': 'Ukrainian',
    'nl': 'Dutch',
    'ms': 'Malay',
    'zh-TW': 'Chinese (Traditional)',
    'ta': 'Tamil',
    'te': 'Telugu',
    'mr': 'Marathi',
    'gu': 'Gujarati',
    'kn': 'Kannada',
    'ml': 'Malayalam',
    'pa': 'Punjabi',
    'si': 'Sinhala',
    'ne': 'Nepali',
    'sw': 'Swahili',
    'he': 'Hebrew',
    'el': 'Greek',
    'cs': 'Czech',
    'sv': 'Swedish',
    'ro': 'Romanian',
    'hu': 'Hungarian',
    'da': 'Danish',
    'fi': 'Finnish',
    'no': 'Norwegian',
    'sk': 'Slovak',
    'bg': 'Bulgarian',
    'sr': 'Serbian',
    'hr': 'Croatian',
    'sl': 'Slovenian',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'et': 'Estonian',
    'sq': 'Albanian',
    'ca': 'Catalan',
    'af': 'Afrikaans',
    'am': 'Amharic',
    'ha': 'Hausa',
    'yo': 'Yoruba',
    'ig': 'Igbo',
    'zu': 'Zulu',
    'so': 'Somali',
    'my': 'Burmese',
    'km': 'Khmer',
    'lo': 'Lao',
    'mn': 'Mongolian',
    'ka': 'Georgian',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    'kk': 'Kazakh',
    'uz': 'Uzbek',
    'ps': 'Pashto',
}


def language_name(code: str) -> str:
    """Best-effort human-readable name for a UI language code, defaulting to English."""
    if not code:
        return LANGUAGE_NAMES['en']
    return LANGUAGE_NAMES.get(code, LANGUAGE_NAMES['en'])
