#!/usr/bin/env python3
"""
VidSEOKit blog builder.

Reads  : blog_src/posts.json          (metadata for every post)
         blog_src/posts/<slug>.html   (article body, HTML fragment)
Writes : web/blog/<slug>.html         (one standalone, crawlable page per post)
         web/blog/index.html          (blog hub)
         web/sitemap.xml, web/robots.txt, web/llms.txt

Run:  python3 blog_src/build_blog.py
"""

import html
import json
import os
import re
from datetime import date

import figures

# ─────────────────────────────────────────────────────────────
#  SITE CONFIG  — edit these two blocks, then re-run the build
# ─────────────────────────────────────────────────────────────
SITE_URL = "https://vidseokit.com"
SITE_NAME = "VidSEOKit"
AUTHOR = "The VidSEOKit Editorial Team"
PUBLISHER_LOGO = SITE_URL + "/images/logo.svg"

# Leave ADSENSE_CLIENT empty until AdSense approves the site. Empty = no ad
# markup is emitted at all (blank/broken ad units are an AdSense policy risk).
ADSENSE_CLIENT = "ca-pub-3988155577590737"            # e.g. "ca-pub-3988155577590737"
ADSENSE_SLOT_IN_ARTICLE = "1234567890"   # e.g. "1234567890"
ADSENSE_SLOT_BOTTOM = "0987654321"       # e.g. "0987654321"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "blog_src")
OUT = os.path.join(ROOT, "web", "blog")
WEB = os.path.join(ROOT, "web")

# Hero images, generated by blog_src/build_images.py. Absent manifest = the
# build still works, it just emits no images (so the blog never breaks because
# someone forgot to run the image step first).
HERO = {}
_hero_manifest = os.path.join(SRC, "hero_manifest.json")
if os.path.exists(_hero_manifest):
    with open(_hero_manifest, encoding="utf-8") as _fh:
        HERO = json.load(_fh)


def hero_meta(post):
    """og:image / twitter:image block for a post. Empty string if no image."""
    h = HERO.get(post["slug"])
    if not h:
        return ""
    return (
        f'\n  <meta property="og:image" content="{SITE_URL}{h["png"]}">'
        f'\n  <meta property="og:image:width" content="{h["w"]}">'
        f'\n  <meta property="og:image:height" content="{h["h"]}">'
        f'\n  <meta property="og:image:alt" content="{html.escape(h["alt"], quote=True)}">'
        f'\n  <meta name="twitter:image" content="{SITE_URL}{h["png"]}">'
        f'\n  <meta name="twitter:image:alt" content="{html.escape(h["alt"], quote=True)}">'
    )


def hero_figure(post):
    """In-article hero. Uses the SVG: ~5 KB and pin-sharp on any display."""
    h = HERO.get(post["slug"])
    if not h:
        return ""
    return (
        f'      <figure class="post-hero">\n'
        f'        <img src="{h["svg"]}" width="{h["w"]}" height="{h["h"]}"\n'
        f'             alt="{html.escape(h["alt"], quote=True)}" fetchpriority="high" decoding="async">\n'
        f'      </figure>'
    )


def hero_thumb(post):
    """Index-card thumbnail. Lazy — these are all below the fold."""
    h = HERO.get(post["slug"])
    if not h:
        return ""
    return (
        f'      <a class="thumb" href="/blog/{post['slug']}.html" tabindex="-1" aria-hidden="true">'
        f'<img src="{h["svg"]}" width="{h["w"]}" height="{h["h"]}" alt="" loading="lazy" decoding="async"></a>\n'
    )


LOGO_SVG = ('<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 6.25v11.5a2.25 2.25 0 '
            '003.36 1.95l10.07-5.75a2.25 2.25 0 000-3.9L9.86 4.3A2.25 2.25 0 006.5 6.25z"/></svg>')

PLAY_SVG = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14l11-7z"/></svg>'


def pretty(d) -> str:
    """'September 7, 2026'. Day is interpolated rather than formatted because
    the no-pad directive is %#d on Windows and %-d elsewhere -- neither is
    portable, and the wrong one silently renders the literal text."""
    if isinstance(d, str):
        d = date.fromisoformat(d)
    return f"{d:%B} {d.day}, {d.year}"


def words(fragment: str) -> int:
    txt = re.sub(r"<[^>]+>", " ", fragment)
    txt = html.unescape(txt)
    return len([w for w in re.split(r"\s+", txt) if w.strip()])


def ad_slot(slot_id: str, label: str) -> str:
    if not (ADSENSE_CLIENT and slot_id):
        return ('\n<!-- Ad slot (%s): add ADSENSE_CLIENT + slot id in '
                'blog_src/build_blog.py and rebuild. -->\n' % label)
    return (
        '\n<div class="ad-slot">\n'
        '  <span class="ad-label">Advertisement</span>\n'
        '  <ins class="adsbygoogle" style="display:block" data-ad-client="%s" '
        'data-ad-slot="%s" data-ad-format="auto" data-full-width-responsive="true"></ins>\n'
        '  <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>\n'
        '</div>\n' % (ADSENSE_CLIENT, slot_id)
    )


def adsense_head() -> str:
    if not ADSENSE_CLIENT:
        return ""
    return ('\n  <script async crossorigin="anonymous" '
            'src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=%s"></script>'
            % ADSENSE_CLIENT)


THEME_SCRIPT = """  <script>
    (function () {
      try {
        var s = localStorage.getItem('ct-theme');
        if (s === 'light') document.documentElement.classList.remove('dark');
        else document.documentElement.classList.add('dark');
      } catch (e) {}
      document.addEventListener('click', function (e) {
        var b = e.target.closest('[data-theme-toggle]');
        if (!b) return;
        document.documentElement.classList.toggle('dark');
        try {
          localStorage.setItem('ct-theme',
            document.documentElement.classList.contains('dark') ? 'dark' : 'light');
        } catch (e) {}
      });
    })();
  </script>"""


def header(depth_prefix: str = "../") -> str:
    return f"""<header class="site-header">
  <div class="header-inner">
    <a class="brand" href="/">{LOGO_SVG}<span>VidSEOKit</span></a>
    <nav class="header-nav" aria-label="Primary">
      <a href="/">Free tools</a>
      <a href="/blog/">Blog</a>
      <button class="theme-btn" type="button" data-theme-toggle aria-label="Toggle dark mode">&#9681;</button>
    </nav>
  </div>
</header>"""


def footer() -> str:
    return f"""<footer class="site-footer">
  <div class="wrap-wide">
    <div class="footer-inner">
      <a class="brand" href="/">{LOGO_SVG}<span>VidSEOKit</span></a>
      <nav class="footer-nav" aria-label="Footer">
        <a href="/blog">Blog</a>
        <a href="/">Tools</a>
        <a href="/about">About</a>
        <a href="/privacy">Privacy Policy</a>
        <a href="/terms">Terms</a>
        <a href="/contact">Contact</a>
      </nav>
      <span>&copy; {date.today().year} {SITE_NAME}</span>
    </div>
    <p class="disclosure">Editorial note: earnings figures on this site are estimates, not
    guarantees &mdash; real revenue depends on your audience, watch time and advertiser demand.
    Some articles link to third-party products; where a link is a paid affiliate link it is
    labelled as such in the article. This site is not affiliated with, endorsed by, or sponsored
    by YouTube or Google.</p>
  </div>
</footer>"""


def render_faq(faq):
    if not faq:
        return ""
    items = "\n".join(
        '  <details><summary>%s</summary><p>%s</p></details>' % (q, a) for q, a in faq
    )
    return '\n<h2 id="faq">Frequently asked questions</h2>\n<div class="faq">\n%s\n</div>\n' % items


def render_endmatter(post):
    # No visible keyword list. A rendered list of target terms at the foot of an
    # article reads as keyword stuffing to both readers and search engines; the
    # terms still travel in the JSON-LD "keywords" property, which is the
    # appropriate place for them.
    src = "\n".join(
        '  <li>%s &mdash; <a href="%s" rel="noopener nofollow" target="_blank">%s</a></li>'
        % (html.escape(t), u, html.escape(u.replace("https://", "")))
        for t, u in post["sources"]
    )
    return f"""
<section class="endmatter">
  <h2>Sources and further reading</h2>
  <ol class="sources">
{src}
  </ol>
</section>"""


def render_related(post, posts):
    i = posts.index(post)
    picks = [posts[(i + n) % len(posts)] for n in (1, 2, 3)]
    cards = "\n".join(
        '    <li class="card"><span class="cat">%s</span>'
        '<h3><a href="/blog/%s.html">%s</a></h3><p>%s</p></li>'
        % (html.escape(p["category"]), p["slug"], html.escape(p["title"]),
           html.escape(p["description"][:110].rsplit(" ", 1)[0] + "…"))
        for p in picks
    )
    return f"""
<section class="related">
  <h2>Keep reading</h2>
  <ul class="card-grid">
{cards}
  </ul>
</section>"""


def json_ld(post):
    url = f"{SITE_URL}/blog/{post['slug']}.html"
    blog_posting = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": post["title"],
        **({"image": [SITE_URL + HERO[post["slug"]]["png"]]} if post["slug"] in HERO else {}),
        "description": post["description"],
        "articleSection": post["category"],
        "keywords": ", ".join(post["keywords"]),
        "wordCount": post["_words"],
        "inLanguage": "en",
        "datePublished": post["date"],
        "dateModified": post.get("updated", post["date"]),
        "mainEntityOfPage": {"@type": "WebPage", "@id": url},
        "url": url,
        "author": {"@type": "Organization", "name": AUTHOR, "url": SITE_URL},
        "publisher": {
            "@type": "Organization",
            "name": SITE_NAME,
            "url": SITE_URL,
            "logo": {"@type": "ImageObject", "url": PUBLISHER_LOGO},
        },
        "isAccessibleForFree": True,
    }
    crumbs = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE_URL},
            {"@type": "ListItem", "position": 2, "name": "Blog", "item": SITE_URL + "/blog/"},
            {"@type": "ListItem", "position": 3, "name": post["title"], "item": url},
        ],
    }
    blocks = [blog_posting, crumbs]
    if post.get("faq"):
        blocks.append({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
                {"@type": "Question", "name": q,
                 "acceptedAnswer": {"@type": "Answer", "text": re.sub(r"<[^>]+>", "", a)}}
                for q, a in post["faq"]
            ],
        })
    return "\n".join(
        '  <script type="application/ld+json">%s</script>'
        % json.dumps(b, ensure_ascii=False, separators=(",", ":")) for b in blocks
    )


def render_post(post, posts, body):
    url = f"{SITE_URL}/blog/{post['slug']}.html"
    desc = html.escape(post["description"], quote=True)
    # Head-only description: search results truncate ~160 chars, while the
    # on-page standfirst is deliberately fuller. Falls back when absent.
    meta_desc = html.escape(post.get("meta_description") or post["description"],
                            quote=True)
    title_tag = html.escape(post["seo_title"], quote=True)
    pretty_date = pretty(post["date"])
    mins = max(1, round(post["_words"] / 220))

    return f"""<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title_tag}</title>
  <meta name="description" content="{meta_desc}">
  <meta name="author" content="{AUTHOR}">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  <link rel="canonical" href="{url}">
  <link rel="icon" href="/favicon.ico">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="{SITE_NAME}">
  <meta property="og:title" content="{html.escape(post['title'], quote=True)}">
  <meta property="og:description" content="{meta_desc}">
  <meta property="og:url" content="{url}">
  <meta property="article:published_time" content="{post['date']}">
  <meta property="article:section" content="{post['category']}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{html.escape(post['title'], quote=True)}">
  <meta name="twitter:description" content="{meta_desc}">{hero_meta(post)}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;800&display=swap">
  <link rel="stylesheet" href="/blog/assets/blog.css">
{json_ld(post)}{adsense_head()}
{THEME_SCRIPT}
</head>
<body>
{header()}

<main class="wrap">
  <nav class="crumbs" aria-label="Breadcrumb">
    <a href="/">Home</a><span>&rsaquo;</span><a href="/blog/">Blog</a><span>&rsaquo;</span>{html.escape(post['category'])}
  </nav>

  <article>
    <header class="post-head">
      <span class="eyebrow">{html.escape(post['category'])}</span>
      <h1>{html.escape(post['title'])}</h1>
      <div class="post-meta">
        <span>By {AUTHOR}</span><span>&middot;</span>
        <time datetime="{post['date']}">{pretty_date}</time><span>&middot;</span>
        <span>{mins} min read</span><span>&middot;</span>
        <span>{post['_words']:,} words</span>
      </div>
      <p class="standfirst">{html.escape(post['description'])}</p>
    </header>
{ad_slot(ADSENSE_SLOT_IN_ARTICLE, "in-article top")}
{body}
{render_faq(post.get('faq'))}
{ad_slot(ADSENSE_SLOT_BOTTOM, "article bottom")}
{render_endmatter(post)}
  </article>
{render_related(post, posts)}
</main>

{footer()}
</body>
</html>
"""


def render_index(posts):
    cats = []
    for p in posts:
        if p["category"] not in cats:
            cats.append(p["category"])
    filters = "\n".join(
        '      <li><button type="button" data-cat="%s" aria-pressed="false">%s</button></li>'
        % (html.escape(c), html.escape(c)) for c in cats
    )
    items = "\n".join(
        f"""    <li data-cat="{html.escape(p['category'])}">
{hero_thumb(p)}      <div class="post-list-body">
      <span class="cat">{html.escape(p['category'])}</span>
      <h2><a href="/blog/{p['slug']}.html">{html.escape(p['title'])}</a></h2>
      <p>{html.escape(p['description'])}</p>
      <span class="meta"><time datetime="{p['date']}">{pretty(p['date'])}</time>
        &middot; {max(1, round(p['_words'] / 220))} min read</span>
      </div>
    </li>""" for p in posts
    )
    item_list = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "VidSEOKit Creator Blog",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "url": f"{SITE_URL}/blog/{p['slug']}.html",
             "name": p["title"]} for i, p in enumerate(posts)
        ],
    }
    return f"""<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Creator Blog &mdash; YouTube SEO, Analytics &amp; Monetization Guides | {SITE_NAME}</title>
  <meta name="description" content="Source-backed guides on YouTube SEO, click-through rate, RPM, keyword research and monetization. {len(posts)} long-form articles, updated regularly.">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  <link rel="canonical" href="{SITE_URL}/blog/">
  <link rel="icon" href="/favicon.ico">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Creator Blog | {SITE_NAME}">
  <meta property="og:url" content="{SITE_URL}/blog/">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;800&display=swap">
  <link rel="stylesheet" href="/blog/assets/blog.css">
  <script type="application/ld+json">{json.dumps(item_list, ensure_ascii=False, separators=(",", ":"))}</script>{adsense_head()}
{THEME_SCRIPT}
</head>
<body>
{header()}

<main class="wrap-wide">
  <div class="index-hero">
    <h1>The Creator Blog</h1>
    <p>Practical, source-backed guides to YouTube SEO, analytics and monetization &mdash;
    written for creators who treat the channel like a business.</p>
    <ul class="filters">
      <li><button type="button" data-cat="all" aria-pressed="true">All</button></li>
{filters}
    </ul>
  </div>

  <ul class="post-list">
{items}
  </ul>
</main>

{footer()}
<script>
  document.querySelector('.filters').addEventListener('click', function (e) {{
    var b = e.target.closest('button');
    if (!b) return;
    var cat = b.dataset.cat;
    this.querySelectorAll('button').forEach(function (x) {{
      x.setAttribute('aria-pressed', String(x === b));
    }});
    document.querySelectorAll('.post-list > li').forEach(function (li) {{
      var show = (cat === 'all' || li.dataset.cat === cat);
      li.style.display = show ? '' : 'none';
    }});
  }});
</script>
</body>
</html>
"""


def dq(v: str) -> str:
    """Escape a Python string for a single-quoted Dart literal."""
    return (v.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$"))


def render_dart(posts):
    rows = []
    for p in posts:
        h = HERO.get(p["slug"])
        img_url = h["svg"].lstrip("../") if h else 'images/blog/%s.jpg' % p["slug"]
        rows.append(
            "  BlogPost(\n"
            "    slug: '%s',\n"
            "    title: '%s',\n"
            "    description: '%s',\n"
            "    category: '%s',\n"
            "    date: '%s',\n"
            "    readMinutes: %d,\n"
            "    imageUrl: '%s',\n"
            "  ),"
            % (dq(p["slug"]), dq(p["title"]), dq(p["description"]),
               dq(p["category"]),
               dq(pretty(p["date"])),
               max(1, round(p["_words"] / 220)),
               dq(img_url))
        )
    body = "\n".join(rows)
    return (
        "// GENERATED FILE - do not edit by hand.\n"
        "// Source: blog_src/posts.json + blog_src/posts/*.html\n"
        "// Regenerate with: python3 blog_src/build_blog.py\n"
        "\n"
        "/// Metadata for one published article under web/blog/.\n"
        "class BlogPost {\n"
        "  final String slug;\n"
        "  final String title;\n"
        "  final String description;\n"
        "  final String category;\n"
        "  final String date;\n"
        "  final int readMinutes;\n"
        "  final String imageUrl;\n"
        "\n"
        "  const BlogPost({\n"
        "    required this.slug,\n"
        "    required this.title,\n"
        "    required this.description,\n"
        "    required this.category,\n"
        "    required this.date,\n"
        "    required this.readMinutes,\n"
        "    required this.imageUrl,\n"
        "  });\n"
        "\n"
        "  /// Path to the standalone, crawlable article page.\n"
        "  String get url => 'blog/$slug.html';\n"
        "}\n"
        "\n"
        "/// Every article, newest first.\n"
        "const List<BlogPost> blogPosts = [\n%s\n];\n" % body
    )


def render_sitemap(posts):
    today = date.today().isoformat()
    urls = [
        (SITE_URL + "/", today, "1.0"),
        (SITE_URL + "/youtube-seo-analyzer", today, "0.9"),
        (SITE_URL + "/youtube-title-generator", today, "0.9"),
        (SITE_URL + "/youtube-thumbnail-ideas", today, "0.9"),
        (SITE_URL + "/youtube-tag-extractor", today, "0.9"),
        (SITE_URL + "/youtube-earnings-calculator", today, "0.9"),
        (SITE_URL + "/youtube-rpm-by-country", today, "0.9"),
        (SITE_URL + "/blog/", today, "0.9"),
        (SITE_URL + "/about", today, "0.6"),
        (SITE_URL + "/contact", today, "0.6"),
        (SITE_URL + "/privacy", today, "0.5"),
        (SITE_URL + "/terms", today, "0.5"),
    ]
    urls += [(f"{SITE_URL}/blog/{p['slug']}.html", p.get("updated", p["date"]), "0.8")
             for p in posts]
    body = "\n".join(
        "  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n"
        "    <changefreq>monthly</changefreq>\n    <priority>%s</priority>\n  </url>"
        % (u, m, pr) for u, m, pr in urls
    )
    ns = "http://www.sitemaps.org/schemas/sitemap/0.9"
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="%s"\n'
            '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
            '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n%s\n</urlset>\n' % (ns, body))


def render_llms_txt(posts):
    """The llmstxt.org summary of the site, for AI crawlers.

    Generated here rather than hand-written: it lists every article, so a
    hand-maintained copy silently goes stale the moment a post is added (it sat
    at 20 entries while the blog had 50).
    """
    today = date.today().isoformat()
    tools = [
        ("YouTube SEO Analyzer", "/",
         "Scores a video's title, description and tags against a target keyword, "
         "then lists the specific changes to make before publishing."),
        ("YouTube Title Generator", "/youtube-title-generator",
         "Turns a video topic into several ready-to-use title options, each written "
         "to a different framing so you can compare angles side by side."),
        ("YouTube Thumbnail Ideas Generator", "/youtube-thumbnail-ideas",
         "Turns a video topic into concrete thumbnail concepts - subject, expression, "
         "overlay text and colour direction - to design or brief from."),
        ("YouTube Tag Extractor", "/youtube-tag-extractor",
         "Reads the public tags off any YouTube video URL, so you can see how videos "
         "already ranking in your niche describe themselves."),
        ("YouTube Earnings Calculator", "/youtube-earnings-calculator",
         "Estimates monthly AdSense revenue from daily views and content niche, as an "
         "RPM-based range rather than a single figure."),
    ]
    reference = [
        ("YouTube RPM by Country", "/youtube-rpm-by-country",
         "What YouTube pays per 1,000 views in the US, UK, Canada, Germany, France and "
         "across Europe, with typical RPM ranges by market."),
        ("Blog", "/blog",
         "In-depth guides on YouTube SEO, the recommendation algorithm, monetization, "
         "RPM and channel analytics."),
    ]
    about = [
        ("About", "/about", "What VidSEOKit is and who builds it."),
        ("Contact", "/contact", "How to reach the team."),
        ("Privacy Policy", "/privacy", "What data is collected and how it is used."),
        ("Terms of Service", "/terms", "Terms governing use of the tools."),
    ]

    out = [
        "# %s" % SITE_NAME, "",
        "> Free YouTube SEO and analytics tools for creators: SEO scoring, AI title and",
        "> thumbnail generation, tag extraction, and AdSense earnings estimation. No",
        "> account required and no paid tier. Written for creators in the US, Canada,",
        "> UK, Ireland, Australia and Europe.", "",
        "Content last reviewed: %s" % today, "",
    ]
    for heading, rows in (("YouTube tools", tools),
                          ("Reference and guides", reference),
                          ("About", about)):
        out += ["## %s" % heading, ""]
        out += ["- [%s](%s%s): %s" % (n, SITE_URL, u, d) for n, u, d in rows]
        out.append("")
    out += ["## Blog articles", ""]
    out += ["- [%s](%s/blog/%s.html)" % (p["title"], SITE_URL, p["slug"]) for p in posts]
    out.append("")
    return "\n".join(out)


def main():
    with open(os.path.join(SRC, "posts.json"), encoding="utf-8") as f:
        posts = json.load(f)

    os.makedirs(OUT, exist_ok=True)
    bodies = {}
    for p in posts:
        path = os.path.join(SRC, "posts", p["slug"] + ".html")
        if not os.path.exists(path):
            print("  MISSING BODY: %s" % p["slug"])
            continue
        with open(path, encoding="utf-8") as f:
            bodies[p["slug"]] = f.read()
        faq_text = " ".join(q + " " + a for q, a in p.get("faq", []))
        p["_words"] = words(bodies[p["slug"]]) + words(faq_text)

    # Newest first, regardless of the order entries were appended to
    # posts.json. Ties keep their file order, so a batch published on one
    # day stays in the sequence the editor chose.
    live = [p for p in posts if p["slug"] in bodies]
    live.sort(key=lambda p: p["date"], reverse=True)

    short = []
    for p in live:
        with open(os.path.join(OUT, p["slug"] + ".html"), "w", encoding="utf-8") as f:
            f.write(render_post(p, live, figures.render(bodies[p["slug"]])))
        flag = "" if p["_words"] >= 1000 else "  <-- UNDER 1000"
        if p["_words"] < 1000:
            short.append(p["slug"])
        print("  %-46s %5d words%s" % (p["slug"] + ".html", p["_words"], flag))

    with open(os.path.join(OUT, "index.html"), "w", encoding="utf-8") as f:
        f.write(render_index(live))
    with open(os.path.join(WEB, "sitemap.xml"), "w", encoding="utf-8") as f:
        f.write(render_sitemap(live))
    with open(os.path.join(WEB, "llms.txt"), "w", encoding="utf-8") as f:
        f.write(render_llms_txt(live))
    dart_dir = os.path.join(ROOT, "lib", "data")
    os.makedirs(dart_dir, exist_ok=True)
    with open(os.path.join(dart_dir, "blog_posts.dart"), "w", encoding="utf-8") as f:
        f.write(render_dart(live))

    total = sum(p["_words"] for p in live)
    print("\n  %d posts | %d total words | avg %d words"
          % (len(live), total, total / max(1, len(live))))
    if short:
        print("  Posts under 1000 words: %s" % ", ".join(short))


if __name__ == "__main__":
    main()
